name: Randomize image metadata daily

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  randomize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install exiftool
        run: |
          sudo apt-get update
          sudo apt-get install -y libimage-exiftool-perl

      # Вот этот шаг меняешь целиком на новый
      - name: Apply requested EXIF/XMP and rename (robust)
        shell: bash
        run: |
          set -u
          IMG_DIR="images"
          mapfile -t FILES < <(find "$IMG_DIR" -type f \( -iname '*.jpg' -o -iname '*.jpeg' \))
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "No JPG files found"; exit 0
          fi

          now="$(date -u +'%Y:%m:%d %H:%M:%S')"

          MODELS=("iPhone 8" "iPhone XR" "iPhone 11" "iPhone 11 Pro" "iPhone 12" "iPhone 12 Pro" "iPhone 13" "iPhone 13 Pro Max" "iPhone 14" "iPhone 15 Pro")
          FNUMS=("1.5" "1.6" "1.8" "2.0")
          METERING=("Pattern" "Pattern")

          for f in "${FILES[@]}"; do
            has_id=$(exiftool -s -s -s -XMP-dc:Identifier "$f" 2>/dev/null | grep -E '^IMG-[0-9]{11}$' || true)
            if [ -n "$has_id" ]; then
              echo "Skip (already processed): $f"
              continue
            fi

            model="${MODELS[$RANDOM % ${#MODELS[@]}]}"
            artist="user$(printf '%04d' $((RANDOM % 10000)))"
            fnum="${FNUMS[$RANDOM % ${#FNUMS[@]}]}"
            metering="${METERING[$RANDOM % ${#METERING[@]}]}"
            rand11="$(tr -dc '0-9' </dev/urandom | head -c 11)"
            identifier="IMG-${rand11}"

            exiftool -overwrite_original \
              -DateTimeOriginal="$now" -CreateDate="$now" -ModifyDate="$now" \
              -Make="Apple" -Model="$model" -Artist="$artist" \
              -FNumber="$fnum" -ApertureValue="$fnum" \
              -ExposureMode="Auto" -WhiteBalance="Auto" -SceneCaptureType="Standard" \
              -LensMake="Apple" -LensModel="Apple" \
              -Flash=0 \
              -MeteringMode="$metering" \
              -XMP-dc:Coverage="Northern America" \
              -XMP-dc:Format="image/jpeg" \
              -XMP-dc:Identifier="$identifier" \
              -XMP-dc:Language="en" \
              -GPS*= \
              "$f" || echo "exiftool warned on: $f"

            dir="${f%/*}"; ext="${f##*.}"
            newpath="${dir}/${identifier}.${ext,,}"
            if [ "$f" != "$newpath" ]; then
              git mv -f "$f" "$newpath" 2>/dev/null || mv -f "$f" "$newpath"
            fi
          done

      - name: Commit changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add images/*
          git commit -m "Randomized metadata $(date -u)" || echo "No changes to commit"
          git push
