name: Randomize image metadata daily

on:
  workflow_dispatch:
  push:
    paths:
      - 'images/**'
      - '.github/workflows/randomize-meta.yml'
  schedule:
    - cron: '0 3 * * *'   # ежедневно 03:00 UTC

permissions:
  contents: write          # нужно для git push из workflow

jobs:
  randomize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # использовать GITHUB_TOKEN для push

      - name: Install exiftool
        run: |
          sudo apt-get update
          sudo apt-get install -y libimage-exiftool-perl

      - name: Apply requested EXIF/XMP and rename (robust)
        shell: bash
        run: |
          set -u
          IMG_DIR="images"
          mapfile -t FILES < <(find "$IMG_DIR" -type f \( -iname '*.jpg' -o -iname '*.jpeg' \))
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "No JPG files found"; exit 0
          fi

          now="$(date -u +'%Y:%m:%d %H:%M:%S')"
          MODELS=("iPhone 8" "iPhone XR" "iPhone 11" "iPhone 11 Pro" "iPhone 12" "iPhone 12 Pro" "iPhone 13" "iPhone 13 Pro Max" "iPhone 14" "iPhone 15 Pro")
          FNUMS=("1.5" "1.6" "1.8" "2.0")
          METERING=("Pattern" "Pattern")  # совместимо с Matrix

          for f in "${FILES[@]}"; do
            echo "Processing: $f"

            # IMG-<11 цифр> без пайпов (чтобы не ловить Broken pipe)
            seed="$(printf '%05d%05d%05d' "$RANDOM" "$RANDOM" "$RANDOM")"
            rand11="${seed:0:11}"
            identifier="IMG-${rand11}"

            model="${MODELS[$RANDOM % ${#MODELS[@]}]}"
            artist="user$(printf '%04d' $((RANDOM % 10000)))"
            fnum="${FNUMS[$RANDOM % ${#FNUMS[@]}]}"
            metering="${METERING[$RANDOM % ${#METERING[@]}]}"

            exiftool -overwrite_original \
              -DateTimeOriginal="$now" -CreateDate="$now" -ModifyDate="$now" \
              -Make="Apple" -Model="$model" -Artist="$artist" \
              -FNumber="$fnum" -ApertureValue="$fnum" \
              -ExposureMode="Auto" -WhiteBalance="Auto" -SceneCaptureType="Standard" \
              -LensMake="Apple" -LensModel="Apple" \
              -Flash=0 \
              -MeteringMode="$metering" \
              -XMP-dc:Coverage="Northern America" \
              -XMP-dc:Format="image/jpeg" \
              -XMP-dc:Identifier="$identifier" \
              -XMP-dc:Language="en" \
              -GPS*= \
              "$f" || echo "exiftool warned on: $f"

            # Переименуем под identifier
            dir="${f%/*}"; ext="${f##*.}"
            newpath="${dir}/${identifier}.${ext,,}"
            if [ "$f" != "$newpath" ]; then
              echo "Renaming to: $newpath"
              git mv -f "$f" "$newpath" 2>/dev/null || mv -f "$f" "$newpath"
            fi
          done

      - name: Commit results
        run: |
          git config user.email "action@github.com"
          git config user.name "meta-bot"
          git add -A
          git commit -m "Randomized metadata $(date -u)" || echo "No changes"
          git push
