name: Randomize image metadata daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # запуск каждый день в 00:00 UTC

jobs:
  randomize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install exiftool
        run: sudo apt-get install -y exiftool

      - name: Apply requested EXIF/XMP and rename (robust)
        run: |
          set -u
          for f in images/*.{jpg,jpeg,JPG,JPEG}; do
            [ -e "$f" ] || continue

            # генерируем IMG-(11 цифр)
            seed="$(printf '%05d%05d%05d' "$RANDOM" "$RANDOM" "$RANDOM")"
            rand11="${seed:0:11}"
            identifier="IMG-${rand11}"

            # случайные параметры
            artist="Author"
            coverage="Northern America"
            date="$(date -u +"%Y:%m:%d %H:%M:%S")"
            format="image/jpeg"
            language="en"
            manufacturer="Apple"

            # случайный выбор из списков
            models=("iPhone 8" "iPhone XR" "iPhone 11" "iPhone 11 Pro" "iPhone 12" "iPhone 12 Pro" "iPhone 13" "iPhone 13 Pro Max" "iPhone 14" "iPhone 15 Pro")
            fnums=("f/1.5" "f/1.6" "f/1.8" "f/2.0")
            metering=("Pattern" "Matrix")

            model="${models[$RANDOM % ${#models[@]}]}"
            fnum="${fnums[$RANDOM % ${#fnums[@]}]}"
            metering_mode="${metering[$RANDOM % ${#metering[@]}]}"

            echo "Обрабатываем: $f → $identifier"

            exiftool -overwrite_original \
              -Artist="$artist" \
              -Coverage="$coverage" \
              -DateTimeOriginal="$date" \
              -FileModifyDate="$date" \
              -Format="$format" \
              -Identifier="$identifier" \
              -Language="$language" \
              -Make="$manufacturer" \
              -Model="$model" \
              -FNumber="$fnum" \
              -ExposureMode="Auto" \
              -WhiteBalance="Auto" \
              -SceneCaptureType="Standard" \
              -LensMake="Apple" \
              -LensModel="Apple" \
              -Flash="Flash did not fire" \
              -MeteringMode="$metering_mode" \
              "$f"
          done

      - name: Commit changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add images/*
          git commit -m "Randomized metadata $(date -u)" || echo "No changes to commit"
          git push
